version: '3'
services:
    order-service:
        build: ./
        environment:
            - OTEL_TRACES_EXPORTER=console
            - OTEL_METRICS_EXPORTER=console
            - OTEL_LOGS_EXPORTER=console
        ports: 
            - "8080:8080"